#BE-1387 Proxy Configuration Page
appcircleio/appcircle-docusaurus pull request #118
Opened 2023-07-22 11:18 UTC by safderun

Added *Proxy Configuration* page for describing how to configure proxy settings for the Appcircle server so that Appcircle containers can reach to resources on the internet.

2023-07-24 11:02 UTC, csonuryilmaz requested changes

2023-07-24 11:02 UTC, csonuryilmaz commented on docs/self-hosted-appcircle/configure-server/proxy-configuration.md
> +
What about restarting Docker or Podman services? Are the changes available while the server is up and running?

We need to give info about these topics.

2023-07-24 14:20 UTC, safderun commented on docs/self-hosted-appcircle/configure-server/proxy-configuration.md
I tested on Ubuntu 22.04 using docker. It is working as expected.

2023-07-27 12:15 UTC, csonuryilmaz approved these changes
(at last) LGTM! :pray:

2023-07-27 12:16 UTC, merged