Added firebase auth errors
appcircleio/appcircle-docusaurus pull request #142
Opened 2023-09-15 15:38 UTC by ftmzhrsckldr

2023-09-18 15:47 UTC, csonuryilmaz commented
@safderun After your review and approval, you can ping me for the final operations. :wink:

2023-09-19 14:02 UTC, safderun requested changes

2023-09-19 14:19 UTC, ftmzhrsckldr commented on docs/troubleshooting-faq/common-issues.md
> +echo $NODE_EXTRA_CA_CERTS
Bash command changed 👍

2023-09-20 04:50 UTC, safderun approved these changes
LGTM 🙌

2023-09-20 06:58 UTC, merged