BE-2160: added new faq document because of min deployment target error
appcircleio/appcircle-docusaurus pull request #181
Opened 2023-11-10 10:38 UTC by boztopuz

2023-11-13 11:32 UTC, csonuryilmaz requested changes
It will get updates from author. [online discussion]

2024-04-19 08:19 UTC, erenkan requested changes

2024-04-19 08:19 UTC, erenkan commented on docs/troubleshooting-faq/common-issues.md
> +We observed that this error occurs with Cocoapods version 1.12.1 and older. Therefore, to resolve this issue, you can either update your local Cocoapods version and make a new commit, or update the C
```suggestion
This error typically occurs with Cocoapods version 1.12.1 and older. To resolve it, update your local Cocoapods to a newer version and commit the changes, or update Cocoapods during the workflow at the Cocoapods Install step.
```

2024-04-19 08:19 UTC, erenkan commented on docs/troubleshooting-faq/common-issues.md
> +If you still encounter this issue after updating the Cocoapods version, please update your iOS minimum deployment target version to iOS 13.0 and higher. If this does not resolve the issue, you can us
```suggestion
If the issue persists after updating Cocoapods, consider updating your iOS minimum deployment target to iOS 13.0 or higher. If the problem still remains, use the script provided below.
```

2024-04-19 08:19 UTC, erenkan commented on docs/troubleshooting-faq/common-issues.md
> +After the release of new Xcode and iOS versions, if your project contains pods or targets that are below a certain iOS version, you will encounter an error related to the simulator, as simulators no
```suggestion
Following the release of new Xcode and iOS versions, projects containing pods or targets below certain iOS versions may experience simulator-related errors due to unsupported older iOS versions.
```

2024-04-19 08:19 UTC, erenkan commented on docs/troubleshooting-faq/common-issues.md
> +You will encounter an error like the following during the 'Xcodebuild for Devices' step:
```suggestion
During the 'Xcodebuild for Devices' step, you may encounter an error similar to this:
```

2024-04-19 08:19 UTC, erenkan commented on docs/troubleshooting-faq/common-issues.md
> +For your pods, you can use the following script at the end of `Podfile`:
```suggestion
For your pods, append the following script to the end of your `Podfile`:
```

2024-04-22 09:02 UTC, erenkan approved these changes

2024-04-24 16:02 UTC, merged