BE-2546 Updated neccesary custom script sample
appcircleio/appcircle-docusaurus pull request #263
Opened 2024-01-16 15:48 UTC by ftmzhrsckldr

2024-02-14 10:21 UTC, csonuryilmaz commented
@ftmzhrsckldr 
> However, although this is a Common Workflow Steps, it was decided to separate this component for iOS and Android, so I added it to separate documents. Github repo links will also be reserved soon.

AFAIK, this decision was canceled. I gave some feedback to @boztopuz, and currently we have a single repository for both iOS and Android.

I assigned @boztopuz as a co-reviewer for the PR. He can share the latest information with us.

2024-02-14 11:01 UTC, burakAppcircle commented on docs/integrations/working-with-custom-scripts/custom-script-samples.md
> +Please note that this custom script must be placed after the [**Test Reports**](http://localhost:3000/workflows/android-specific-workflow-steps#test-reports-for-android) step in the workflow..
Double dot at the end of sentence. "....step in the workflow.."

2024-02-14 11:04 UTC, burakAppcircle commented on docs/integrations/working-with-custom-scripts/custom-script-samples.md
> +file_path = "#{output_dir}/test_results.json"
'test_result_file_path' instead of 'file_path'. 

It is being used as 'test_result_file_path' in the line 92

2024-02-14 11:10 UTC, boztopuz commented on docs/integrations/working-with-custom-scripts/custom-script-samples.md
> +file_path = "#{output_dir}/test_results.json"
'test_result_file_path' instead of 'file_path'.

It is being used as 'test_result_file_path' in the line 92

2024-02-14 11:10 UTC, boztopuz commented on docs/integrations/working-with-custom-scripts/custom-script-samples.md
> +You may also use our Firebase App Distribution Component for this process.
We can give a link to make a directions to the related component documentation page.

2024-02-14 11:17 UTC, boztopuz commented
I added some feedback for typos @csonuryilmaz .

Apart from feedbacks, our decision about the test report component was as follows. 

@ftmzhrsckldr 
Repo status
The repository of the component is common, and the platform is controlled in main.rb, and the relevant parser classes are called and executed based on the platform. While developing, we separated it into iOS and Android only on the workflow component and set the Jacoco selection to appear only on the Android side.

@csonuryilmaz 
Document status
Since these Test Report Comp. details are explained under a tab called 'Continues Testing' in the folder tree on the left side in Appcircle documents, there are no documents for these steps in iOS and Android specific workflows. If the 'Continues testing' tab is removed after organizing the folder structure, they will need to be added to the document as iOS and Android specific. 

@csonuryilmaz 
My opinion is that the 'Continues Testing' tab should NOT be removed. Since Unit and UI Testing is a big topic in itself, it should stand out and be explained in detail in a special tab.

2024-02-14 11:25 UTC, boztopuz requested changes
Some changes are necessary according to feedbacks.

2024-03-01 08:45 UTC, csonuryilmaz commented
>  'Continuous Testing' tab should NOT be removed ...

I agree. :+1:

2024-03-12 15:10 UTC, ftmzhrsckldr commented
> Some changes are necessary according to feedbacks.

@boztopuz Feedbacks have been fixed, can you check again?

2024-03-12 15:54 UTC, boztopuz approved these changes
@csonuryilmaz I checked, links are good, grammer checked. I approve.

2024-03-15 09:55 UTC, csonuryilmaz approved these changes

2024-03-15 09:55 UTC, merged