#BE-2803 Okta SAML Documentation Update
appcircleio/appcircle-docusaurus pull request #311
Opened 2024-02-20 14:18 UTC by atkncamurcu

2024-03-01 10:13 UTC, burakberkkeskin commented
- The document page overviews are missing. What is the document page is describing, what will happend when the follow the page?

- There is no overview for [LDAP](https://deploy-preview-311--reverent-galileo-8ef035.netlify.app/account/ldap-login).

- There is no overview for [SSO Login Dist & Store](https://deploy-preview-311--reverent-galileo-8ef035.netlify.app/account/sso-login/single-sign-on-login)

2024-03-01 10:13 UTC, burakberkkeskin commented
- I added some cautions about self-hosted and some directives.
- The okta configuration for the Appcircle dashboard login should also be edited as in okta dist and store page.

2024-03-01 10:15 UTC, burakberkkeskin commented
- After the Dist and Store SSO configuration is done, there is no detailed description or page about how to enable SSO for dist and store profiles in the [page](https://deploy-preview-311--reverent-galileo-8ef035.netlify.app/account/sso-login/okta-saml/).

2024-03-01 10:21 UTC, burakberkkeskin requested changes

2024-03-01 10:21 UTC, burakberkkeskin commented on docs/account/sso-login/okta-saml.md
> +- You can enable the SSO Login in Enterprise App Store Settings
After the SSO integration is done, there is no detailed description or page about how to enable SSO for dist and store profiles in the page.

2024-03-01 10:21 UTC, burakberkkeskin commented on docs/account/sso/okta-saml.md
- The document page overviews are missing. What is the document page describing? What will happen when someone follows the page?
- I added some cautions about self-hosted and some directives.
- The okta configuration for the Appcircle dashboard login should also be edited, as in the Okta dist and store page.

2024-03-01 10:21 UTC, burakberkkeskin commented on docs/account/ldap-login.md
> +
The document page overviews are missing. What is the document page describing? What will happen when someone follows the page?

2024-03-01 10:21 UTC, burakberkkeskin commented on docs/account/sso-login/okta-saml.md
> +
The document page overviews are missing. What is the document page describing? What will happen when someone follows the page?

2024-03-07 12:07 UTC, csonuryilmaz approved these changes

2024-03-07 12:09 UTC, merged