[BE-2796]: Added node ınstall step doc
appcircleio/appcircle-docusaurus pull request #314
Opened 2024-02-21 16:39 UTC by boztopuz

2024-03-06 15:34 UTC, ftmzhrsckldr requested changes

2024-03-06 15:34 UTC, ftmzhrsckldr commented on docs/integrations/react-specific-workflow-steps/node-install.md
> +| [**npm/yarn Commands**](https://docs.appcircle.io/workflows/react-native-specific-workflow-steps#npmyarn-commands) | This step runs npm/yarn with the given commands. Please use the [**Install Node*
@boztopuz Here you said that this `npm/yarn Commands` step, should be used before this step. 
However, you added it in the Prerequisites table below.
Can you please fix the logical error here?
If it needs to be used afterwards, there should be a warning, but it should not be in the Prerequisites table.

2024-03-06 15:34 UTC, ftmzhrsckldr commented on docs/integrations/react-specific-workflow-steps/node-install.md
> +If you do not specify any specific version for the **Install Node** step. The latest version will be installed automatically.
@boztopuz Could you please add this inout to the table to preserve the pattern we created?

2024-03-06 15:35 UTC, ftmzhrsckldr requested changes

2024-03-06 15:35 UTC, ftmzhrsckldr commented on docs/integrations/react-specific-workflow-steps/node-install.md
> +https://github.com/appcircleio/appcircle-node-install-component
@boztopuz Can you add this desc:
> To access the source code of this component, please use the following link:

2024-03-08 12:27 UTC, boztopuz commented
@ftmzhrsckldr its ready to review again. fyi.

2024-03-13 02:31 UTC, merged