#BE-2812 Enterprise App Store Beta/Live Docs Update
appcircleio/appcircle-docusaurus pull request #317
Opened 2024-02-22 12:12 UTC by atkncamurcu

2024-03-01 10:59 UTC, burakberkkeskin requested changes

2024-03-01 10:59 UTC, burakberkkeskin commented on docs/account/sso-login/okta-saml.md
> +
Overview is missing. Why should users want to manager user groups from okta?
We can refer to the store behaviour (beta access none by default, live access all by default).

2024-03-01 10:59 UTC, burakberkkeskin commented on docs/account/sso-login/okta-saml.md
> +
We might give an example use case here for the store.

For example there are two groups, one is `developers` and other one is `users`.

The beta channel should be available for `developers` group and not for `users` group.
The live channel should be available for both groups.

2024-03-07 11:45 UTC, csonuryilmaz approved these changes

2024-03-07 11:46 UTC, merged