[BE-2571]: Added convert result xml html doc
appcircleio/appcircle-docusaurus pull request #376
Opened 2024-03-14 13:57 UTC by boztopuz

2024-03-14 20:46 UTC, ftmzhrsckldr approved these changes

2024-04-17 12:46 UTC, erenkan requested changes

2024-04-17 12:46 UTC, erenkan commented on docs/integrations/ios-specific-workflow-steps/convert-xcresult-xml-html.md
> +---
You should change this section based on latest documentation best practices eg:

```yaml
---
title: Title of the Document
description: A concise SEO-friendly description, limited to 160 characters.
tags: [tag1, tag2, tag3]
---

2024-04-18 06:44 UTC, boztopuz commented
@erenkan this is the old PR. I forgot to close this PR. It has been renew with #386. Onur's comment in linear is https://linear.app/appcircle/issue/BE-2571/xcresult-converter-doc-update#comment-baee29af

2024-04-18 07:38 UTC, closed without merging