Added Azure bot for detekt doc
appcircleio/appcircle-docusaurus pull request #379
Opened 2024-03-15 10:26 UTC by ftmzhrsckldr

2024-03-16 11:14 UTC, boztopuz approved these changes

2024-04-17 12:41 UTC, erenkan requested changes

2024-04-17 12:41 UTC, erenkan commented on docs/integrations/android-specific-workflow-steps/azure-bot-for-detekt-report.md
> +---
You should change this section based on latest documentation best practices eg:

```yaml
---
title: Title of the Document
description: A concise SEO-friendly description, limited to 160 characters.
tags: [tag1, tag2, tag3]
---

2024-04-18 17:13 UTC, ftmzhrsckldr commented
This PR will close for conflict. New PR: #422

2024-04-18 17:13 UTC, closed without merging