[BE-2990]: Marathon Cloud docs added
appcircleio/appcircle-docusaurus pull request #387
Opened 2024-03-21 07:35 UTC by boztopuz

2024-03-21 13:06 UTC, ftmzhrsckldr requested changes
I made the corrections but please pass after checking. Just to make sure I didn't make a mistake on the iOS side.

2024-03-21 13:06 UTC, ftmzhrsckldr commented on docs/integrations/common-workflow-steps/marathon-cloud.md
> +| `$AC_MARATHON_UITEST_RUNNER_APP_PATH` | This path will be generated by relevant testing step(`Android Build for UI Testing` or `Xcodebuild for Testing`). | Required |
```suggestion
| `$AC_MARATHON_UITEST_RUNNER_APP_PATH` | Specifies the path to the test application binary. This application is generated by the corresponding testing step (**Android Build for UI Testing** or **Xcodebuild for Testing**). The default value is `AC_TEST_APK_PATH ` for Android or `AC_UITESTS_RUNNER_PATH` for iOS. | Required |
```

2024-03-21 13:06 UTC, ftmzhrsckldr commented on docs/integrations/common-workflow-steps/marathon-cloud.md
> +| `$AC_OUTPUT_DIR`              | Specifies the path for Marathon Cloud outputs. | Required |
Could you please specify that this will be automatically identified? so the user does not have to search for this value.

2024-03-22 09:34 UTC, ftmzhrsckldr approved these changes

2024-04-17 12:38 UTC, erenkan requested changes

2024-04-17 12:38 UTC, erenkan commented on docs/integrations/common-workflow-steps/marathon-cloud.md
> +
You should change this section based on latest documentation best practices eg: 

```suggestion
---
- **title**: The title of the document.
- **description**: his is critical for SEO. Keep it under 160 characters to ensure full visibility in search engine results.
- **tags**: Include relevant tags that describe the document's content. This helps in categorizing the documentation.
sidebar_position: 1
---

```

2024-04-18 07:28 UTC, erenkan approved these changes

2024-04-18 07:28 UTC, merged