[BE-3152]: Added FOD docs
appcircleio/appcircle-docusaurus pull request #429
Opened 2024-04-20 10:00 UTC by boztopuz

2024-04-20 10:01 UTC, boztopuz commented
@ftmzhrsckldr could you please check the Android side requirements that I mentioned in documentation.

2024-04-22 07:56 UTC, erenkan requested changes

2024-04-22 07:56 UTC, erenkan commented on docs/workflows/common-workflow-steps/fod-mobile-assesment.md
> +Fortify on Demand Mobile Assessment can be seamlessly integrated into your workflow with Appcircle, enabling easy setup and utilization within your existing development processes.
```suggestion
You can seamlessly integrate Fortify on Demand Mobile Assessment into your workflow with Appcircle, facilitating easy setup and utilization within your existing development processes.
```

2024-04-22 07:56 UTC, erenkan commented on docs/workflows/common-workflow-steps/fod-mobile-assesment.md
> +Before running the **Fortify on Demand Mobile Assessment** step, certain prerequisites must be completed. These prerequisites, detailed in the table below:
```suggestion
Before running the **Fortify on Demand Mobile Assessment** step, you must complete certain prerequisites, as detailed in the table below:
```

2024-04-22 07:56 UTC, erenkan commented on docs/workflows/common-workflow-steps/fod-mobile-assesment.md
> +| [**Android Sign**](/workflows/android-specific-workflow-steps/android-sign) | If a signed app is created, this step needs to be run beforehand to process this output.|
```suggestion
| [**Android Sign**](/workflows/android-specific-workflow-steps/android-sign) | If you create a signed app, you must run this step beforehand to process the output. |
```

2024-04-22 07:56 UTC, erenkan commented on docs/workflows/common-workflow-steps/fod-mobile-assesment.md
> +| `$AC_FOD_ENTITLEMENT_ID`      | The ID assigned to ypur current entitlement. This value can be reterived in Foritfy on Demand portal.     | Required |
```suggestion
| `$AC_FOD_ENTITLEMENT_ID`      | The ID assigned to your current entitlement. You can retrieve this value in the Fortify on Demand portal.     | Required |
```

2024-04-22 07:56 UTC, erenkan commented on docs/workflows/common-workflow-steps/fod-mobile-assesment.md
> +| `$AC_FOD_CLIENT_DATACENTER`   | Select the datacenter assigned to you. This is provided once your are onboarded with Fortify on Demand.   | Required |
```suggestion
| `$AC_FOD_CLIENT_DATACENTER`   | Select the datacenter assigned to you upon your onboarding with Fortify on Demand.   | Required |
```

2024-04-22 08:12 UTC, erenkan approved these changes

2024-04-22 08:48 UTC, merged

2024-04-22 09:08 UTC, ftmzhrsckldr commented on docs/workflows/common-workflow-steps/fod-mobile-assesment.md
> +### Prerequisites
Flutter iOS and Android should be added too. 
The Prerequisites table should be under each platform heading.
You can examine it as an example:
- https://docs.appcircle.io/workflows/common-workflow-steps/firebase-app-distribution#prerequisites