Added Get Approval via Email doc
appcircleio/appcircle-docusaurus pull request #488
Opened 2024-05-21 11:18 UTC by ftmzhrsckldr

2024-05-21 17:57 UTC, boztopuz requested changes

2024-05-21 17:57 UTC, boztopuz commented on docs/publish-integrations/common-publish-integrations/get-approval-from-email.md
> +
@ftmzhrsckldr with last release, we changed the log structure of this step, maybe we can put it into here. I shared the example screen shot

2024-05-22 09:08 UTC, boztopuz approved these changes

2024-05-22 09:45 UTC, erenkan requested changes

2024-05-22 09:45 UTC, erenkan commented on docs/publish-integrations/common-publish-integrations/get-approval-from-email.md
> +If some optional users reject, but there is still a chance to achieve the minimum approval count, the step will remain in `Waiting` status, awaiting responses from other users. For instance, if the m
```suggestion
If some optional users reject the request but there is still a chance to achieve the minimum approval count, the step will remain in `Waiting` status, awaiting responses from other users. For instance, if you set the minimum approval count to 3, and out of 10 users, only one is required, the step can still succeed. Even if 7 non-required users reject, the approval can still be obtained from the remaining 3 users. However, if 8 non-required users reject, the step will fail, as it is no longer possible to meet the minimum requirement of 3 approvals.
```

2024-05-22 09:45 UTC, erenkan commented on docs/publish-integrations/common-publish-integrations/get-approval-from-email.md
> +When the step restarts or begins, all answers will be reset to `Waiting`, and users must provide their answers again. Consequently, they will receive approval emails again.
```suggestion
Upon restarting or initiating the step, it resets all answers to `Waiting`. Users must then provide their answers again and will receive new approval emails.
```

2024-05-22 12:23 UTC, erenkan approved these changes

2024-05-22 12:23 UTC, merged