Added FAQ to Google API Key
appcircleio/appcircle-docusaurus pull request #491
Opened 2024-05-21 15:48 UTC by ftmzhrsckldr

2024-05-21 18:08 UTC, boztopuz approved these changes

2024-05-21 18:08 UTC, boztopuz commented on docs/account/my-organization/api-integrations/adding-google-play-service-account.md
> +    a. Navigate to [My Organization](/account/my-organization)n.
```suggestion
    a. Navigate to [My Organization](/account/my-organization).
```

2024-05-21 18:08 UTC, boztopuz commented on docs/account/my-organization/api-integrations/adding-google-play-service-account.md
> +    a. Navigate to [My Organization](/account/my-organization)n.
@ftmzhrsckldr I fixed this typo. Thnks for your effort. I approved

2024-05-22 09:30 UTC, erenkan requested changes

2024-05-22 09:30 UTC, erenkan commented on docs/account/my-organization/api-integrations/adding-google-play-service-account.md
> +No, for security reasons, the JSON file you uploaded cannot be downloaded again from Appcircle.
```suggestion
No, for security reasons, you cannot download the JSON file you uploaded to Appcircle again.
```

2024-05-22 09:30 UTC, erenkan commented on docs/account/my-organization/api-integrations/adding-google-play-service-account.md
> +**After uploading the JSON, why can't I save it?**
```suggestion
**Why can’t I save the JSON after uploading it?**
```

2024-05-22 09:30 UTC, erenkan commented on docs/account/my-organization/api-integrations/adding-google-play-service-account.md
> +You may have skipped the first step. Please ensure you have enabled the Service account.
```suggestion
You might have missed the first step. Please ensure that you have enabled the Service Account.
```

2024-05-22 10:31 UTC, erenkan approved these changes

2024-05-22 10:34 UTC, merged