Added new publish features, and register bundleID feature doc
appcircleio/appcircle-docusaurus pull request #515
Opened 2024-06-13 08:39 UTC by boztopuz

2024-06-24 12:50 UTC, SarpBakis23 commented on docs/signing-identities/bundle-id-registration.md
> +### Manuel Register Bundle Identifier
```suggestion
### Manual Register Bundle Identifier
```

2024-06-24 12:51 UTC, SarpBakis23 commented on docs/signing-identities/bundle-id-registration.md
> +The BundleID option in Appcircle's Signing Identities module, you can easily register a BundleID on the Apple Developer Portal or list your existing BundleIDs on Appcircle.
```suggestion
With the BundleID option in Appcircle's Signing Identities module, you can easily register a BundleID on the Apple Developer Portal or list your existing BundleIDs on Appcircle.
```

2024-06-24 12:53 UTC, SarpBakis23 commented on docs/signing-identities/bundle-id-registration.md
> +:::info Manuel Register Bundle Identifier
```suggestion
:::info Manual Register Bundle Identifier
```

2024-06-24 12:57 UTC, SarpBakis23 commented on docs/signing-identities/bundle-id-registration.md
> +When you register a BundleID, it will be simultaneously created in your Apple Developer account.
```suggestion
When you register a BundleID, it will be created simultaneously in your Apple Developer account.
```

2024-06-24 13:02 UTC, SarpBakis23 commented on docs/signing-identities/bundle-id-registration.md
> +In the Edit screen, you can see all the capabilitiy it has in BundleID and you can add or remove them if you wish.
```suggestion
In the Edit screen, you can view all the capabilities associated with the BundleID, and you can add or remove them as needed.
```

2024-06-24 13:04 UTC, SarpBakis23 commented on docs/publish-module/binary-management/index.md
> +You can install iOS app versions with different BundleIDs under the same Publishing Profile. However, you can start the Publish process with the binary with the BundleID value specified when creating
```suggestion
You can install iOS app versions with different BundleIDs under the same Publishing Profile. However, you can only initiate the Publish process with the binary that matches the BundleID specified when creating the profile or within the profile itself.
```

2024-06-24 13:10 UTC, SarpBakis23 commented on docs/signing-identities/bundle-id-registration.md
> +The changes you make here will be **simultaneously** modified and saved in your Apple Developer account.
```suggestion
The changes you make here will be modified **simultaneously** and saved in your Apple Developer account.
```

2024-06-24 13:12 UTC, SarpBakis23 requested changes
could you please update the suggestion marked areas

2024-06-27 06:04 UTC, boztopuz commented
@SarpBakis23 I deleted the bundle registration doc because I transfered it to #522 PR and fixed all feedbacks about it in the new PR

2024-06-27 07:05 UTC, SarpBakis23 approved these changes
approved

2024-06-27 07:09 UTC, merged