#BE-4293 Added Base VM Cautions
appcircleio/appcircle-docusaurus pull request #625
Opened 2024-09-03 13:34 UTC by burakberkkeskin

2024-09-04 13:02 UTC, hiilhan requested changes

2024-09-04 13:02 UTC, hiilhan commented on docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
> +It's not recommended to delete the base image (`macOS_240514`) as it won't save disk space due to copy-on-write file system on macOS. You can safely re-create `vm01` from the same base image `macOS_2
We may generalize the base image name like `macOS_YYMMDD`, `macOS_<version-code>`. Or indicating it is an example: 
> It's not recommended to delete the base image (e.g., `macOS_240514`) as it won't save disk space due to copy-on-write file system on macOS. You can safely re-create `vm01` from the same base image (e.g., `macOS_240514`) without downloading and extracting again from network if needed.

2024-09-05 12:45 UTC, csonuryilmaz commented on docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
> +xcrun simctl delete <runtime_id>
```
xcrun simctl runtime delete <runtime_id>
```

2024-09-05 12:46 UTC, csonuryilmaz commented on docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
> +If you determine that certain watchOS or tvOS runtimes are not needed, you can delete them to free up disk space:
iOS, watchOS, tvOS or visionOS

2024-09-05 12:52 UTC, csonuryilmaz commented on docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
> +If you're freshly creating the base VMs, you can ignore this warning. However, if you've already registered runners to your Appcircle server and want to make updates to the base VMs, it's highly reco
`docs` ❌

2024-09-05 13:35 UTC, merged