Added build token ID expired time as a caution
appcircleio/appcircle-docusaurus pull request #772
Opened 2024-12-17 15:22 UTC by ftmzhrsckldr

2024-12-18 11:38 UTC, boztopuz approved these changes

2025-01-06 05:31 UTC, csonuryilmaz requested changes

2025-01-06 05:31 UTC, csonuryilmaz commented on docs/workflows/common-workflow-steps/build-cache/cache-pull.md
> +:::
@ftmzhrsckldr If we need the same section (_not a single sentence but a meaningful unit as a block_) in different places, then it will be better to make it as a component and reuse it in the required places.

It will make it easy for future updates and will eliminate the possible maintenance issues that can occur when missed.

You can find the relevant samples in the self-hosted documents. @burakberkkeskin can also help you if you need it.

2025-01-08 13:45 UTC, ftmzhrsckldr commented on docs/workflows/common-workflow-steps/build-cache/cache-pull.md
> +:::
@csonuryilmaz Thx. I didn't know we could use components in the documentation. I consulted Berk and updated the code accordingly. Berk approved. FYI.

2025-01-08 13:58 UTC, merged